import { Navegation } from "../components/Navegation";
import { PaginationProvider } from "./../contexts/PaginationProvider";
import "./../styles/globals.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className="backgraund">
        <Navegation></Navegation>
        <PaginationProvider>
          {children}
        </PaginationProvider>
      </body>
    </html>
  );
}
